language: ruby
rvm:
  - 2.0.0
env:
  - DB=postgresql
script:
  - bundle exec rake spec
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - bundle exec rake db:create RAILS_ENV=test
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
bundler_args: --binstubs=./bundler_stubs
before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc' # skip installing docs for gems